/*
 * main.cpp  —  Entry point for the mini-language scanner.
 *
 * Reads source from stdin (or a file passed as argv[1]),
 * runs the Flex-generated lexer, then writes every token
 * to "tokens.out" in the format:
 *
 *   TOKEN_TYPE(lexeme)   — for T_ID, T_INTEGER, T_STRING_LITERAL, T_UNKNOWN
 *   TOKEN_TYPE           — for all other types
 *
 * Build:
 *   flex -o scanner.cpp scanner.l
 *   g++ -std=c++17 -o scanner main.cpp scanner.cpp
 *
 * Run:
 *   ./scanner < source.txt          # read from stdin
 *   ./scanner source.txt            # read from file
 */

#include <iostream>
#include <fstream>
#include <vector>
#include <string>
#include <cstdio>    // FILE, fopen
#include "tokens.h"

// Defined in scanner.cpp (generated by Flex)
extern int  yylex();
extern FILE* yyin;

// Global token list populated by the scanner rules in scanner.l
std::vector<Token> g_tokens;

// Writes the token list to a file.
// Each line: TOKEN_TYPE  or  TOKEN_TYPE(lexeme)
static bool writeTokensToFile(const std::string& path) {
    std::ofstream out(path);
    if (!out.is_open()) {
        std::cerr << "Error: cannot open output file '" << path << "'\n";
        return false;
    }

    for (const Token& tok : g_tokens) {
        switch (tok.type) {
            case T_ID:
            case T_INTEGER:
            case T_STRING_LITERAL:
            case T_UNKNOWN:
                out << tokenTypeName(tok.type) << "(" << tok.lexeme << ")\n";
                break;
            default:
                out << tokenTypeName(tok.type) << "\n";
                break;
        }
    }

    out.close();
    return true;
}

int main(int argc, char* argv[]) {
    // Optionally accept a source file as the first argument.
    if (argc > 1) {
        FILE* f = std::fopen(argv[1], "r");
        if (!f) {
            std::cerr << "Error: cannot open input file '" << argv[1] << "'\n";
            return 1;
        }
        yyin = f;
    }
    // Otherwise yylex() defaults to reading from stdin.

    // Run the lexer to completion; scanner.l rules populate g_tokens
    // and print tokens to stdout as they are recognised.
    yylex();
    std::cout << "\n";   // newline after the inline stdout stream

    // Write the collected tokens to a file for the future parser.
    const std::string outPath = "tokens.out";
    if (!writeTokensToFile(outPath)) {
        return 1;
    }

    std::cerr << "\nScanned " << g_tokens.size()
              << " token(s). Written to '" << outPath << "'.\n";

    if (argc > 1) {
        std::fclose(yyin);
    }
    return 0;
}